<?php

namespace AppBundle\Repository;

/**
 * AccionEstadoParteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionEstadoParteRepository extends \Doctrine\ORM\EntityRepository
{
}
