<?php

namespace AppBundle\Repository;

/**
 * AccionEstadoSancionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionEstadoSancionRepository extends \Doctrine\ORM\EntityRepository
{
}
