<?php

namespace AppBundle\Repository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAlumno($userId){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select("a")
            ->from("AppBundle:Alumno", "a")
            ->where("a.id = :id")
            ->setParameter("id", $userId)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * Función que devuelve los alumnos por curso
     * @param $curso
     * @return array
     */
    public function getAlumnosByCurso($curso){
        $qb = $this->getEntityManager()->createQuery(
          'SELECT a
           FROM AppBundle\Entity\Alumno a
           WHERE a.idCurso = :curso'
        );

        $qb->setParameter('curso', $curso);
        return $qb->getResult();
    }

}
