<?php

namespace AppBundle\Repository;

/**
 * ConductasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConductasRepository extends \Doctrine\ORM\EntityRepository
{
}
