<?php

namespace AppBundle\Repository;

/**
 * DetalleDiarioSancionHoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleDiarioSancionHoraRepository extends \Doctrine\ORM\EntityRepository
{
}
