<?php

namespace AppBundle\Repository;

/**
 * DiarioAulaConvivenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiarioAulaConvivenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
