<?php

namespace AppBundle\Repository;

/**
 * EstadosSancionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosSancionRepository extends \Doctrine\ORM\EntityRepository
{
}
