<?php

namespace AppBundle\Repository;

/**
 * EstadosParteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosParteRepository extends \Doctrine\ORM\EntityRepository
{
}
