<?php

namespace AppBundle\Repository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPerfil($id){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select("p.perfil")
            ->from("AppBundle:Perfil", "p")
            ->where("p.id = :id")
            ->setParameter("id", $id)
            ->getQuery()
            ->getSingleResult();
    }

    public function getPerfiles(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select("p.perfil, p.id")
            ->from('AppBundle:Perfil', 'p')
            ->getQuery()
            ->getResult();
    }

}
