<?php

namespace AppBundle\Repository;

/**
 * RecuperaPuntosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuperaPuntosRepository extends \Doctrine\ORM\EntityRepository
{
}
