<?php

namespace AppBundle\Repository;

/**
 * TipoSancionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSancionRepository extends \Doctrine\ORM\EntityRepository
{
}
