<?php

namespace AppBundle\Repository;

/**
 * TiposConductaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposConductaRepository extends \Doctrine\ORM\EntityRepository
{
}
