<?php

namespace AppBundle\Repository;

/**
 * TipoParteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoParteRepository extends \Doctrine\ORM\EntityRepository
{
}
