<?php

namespace AppBundle\Repository;

/**
 * TutoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutoresRepository extends \Doctrine\ORM\EntityRepository
{
}
