# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.alumnoHelper:
        class: AppBundle\Services\AlumnoHelper
        arguments: ['@doctrine.orm.entity_manager']
    app.importHelper:
        class: AppBundle\Services\ImportHelper
        arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder']
    app.crearSancionHelper:
        class: AppBundle\Services\CrearSancionHelper
        arguments: ['@doctrine.orm.entity_manager']
    app.diarioHelper:
        class: AppBundle\Services\DiarioHelper
        arguments: ['@doctrine.orm.entity_manager']
    app.partesHelper:
        class: AppBundle\Services\PartesHelper
        arguments: ['@doctrine.orm.entity_manager', '@app.crearSancionHelper']

    form.parteType:
        class: AppBundle\Form\ParteFormType
        arguments: ["@doctrine.orm.entity_manager"]
        tags: [ name: ParteFormType ]
