# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.alumnoHelper:
        class: AppBundle\Services\AlumnoHelper
        arguments: ['@doctrine.orm.entity_manager']
    form.parteType:
        class: AppBundle\Form\ParteFormType
        arguments: ["@doctrine.orm.entity_manager"]
        tags: [ name: ParteFormType ]
