<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Alumno extends \AppBundle\Entity\Alumno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'idUsuario', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'idTutor', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'apellido1', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'apellido2', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'nie', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'idCurso', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'codigoPostal', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'foto', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'puntos', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'puntosIniciales'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'idUsuario', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'idTutor', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'apellido1', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'apellido2', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'nie', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'idCurso', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'codigoPostal', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'foto', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'puntos', '' . "\0" . 'AppBundle\\Entity\\Alumno' . "\0" . 'puntosIniciales'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Alumno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNombreCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCompleto', []);

        return parent::getNombreCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCompletoYCurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCompletoYCurso', []);

        return parent::getNombreCompletoYCurso();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido1($apellido1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido1', [$apellido1]);

        return parent::setApellido1($apellido1);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido1', []);

        return parent::getApellido1();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido2($apellido2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido2', [$apellido2]);

        return parent::setApellido2($apellido2);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido2', []);

        return parent::getApellido2();
    }

    /**
     * {@inheritDoc}
     */
    public function setNie($nie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNie', [$nie]);

        return parent::setNie($nie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNie', []);

        return parent::getNie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCurso($idCurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCurso', [$idCurso]);

        return parent::setIdCurso($idCurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCurso', []);

        return parent::getIdCurso();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTutor', []);

        return parent::getIdTutor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTutor($idTutor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTutor', [$idTutor]);

        return parent::setIdTutor($idTutor);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntos($puntos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntos', [$puntos]);

        return parent::setPuntos($puntos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntos', []);

        return parent::getPuntos();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\AppBundle\Entity\Usuarios $idUsuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$idUsuario]);

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal($codigoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        return parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', []);

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', [$foto]);

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntosIniciales($puntosIniciales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntosIniciales', [$puntosIniciales]);

        return parent::setPuntosIniciales($puntosIniciales);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntosIniciales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntosIniciales', []);

        return parent::getPuntosIniciales();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdTutor(\AppBundle\Entity\Tutores $idTutor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdTutor', [$idTutor]);

        return parent::addIdTutor($idTutor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdTutor(\AppBundle\Entity\Tutores $idTutor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdTutor', [$idTutor]);

        return parent::removeIdTutor($idTutor);
    }

}
