<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sanciones extends \AppBundle\Entity\Sanciones implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaInicio', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaFinal', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'sancion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'evaluacion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'puntosRecuperados', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaConfirmacion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaComunicacion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idTipo', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idEstado', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idAlumno', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idParte'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaInicio', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaFinal', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'sancion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'evaluacion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'puntosRecuperados', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaConfirmacion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'fechaComunicacion', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idTipo', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idEstado', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idAlumno', '' . "\0" . 'AppBundle\\Entity\\Sanciones' . "\0" . 'idParte'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sanciones $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', [$fechaInicio]);

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', []);

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinal($fechaFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinal', [$fechaFinal]);

        return parent::setFechaFinal($fechaFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinal', []);

        return parent::getFechaFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSancion($sancion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSancion', [$sancion]);

        return parent::setSancion($sancion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSancion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSancion', []);

        return parent::getSancion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluacion($evaluacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluacion', [$evaluacion]);

        return parent::setEvaluacion($evaluacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluacion', []);

        return parent::getEvaluacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntosRecuperados($puntosRecuperados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntosRecuperados', [$puntosRecuperados]);

        return parent::setPuntosRecuperados($puntosRecuperados);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntosRecuperados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntosRecuperados', []);

        return parent::getPuntosRecuperados();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipo', []);

        return parent::getIdTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipo($idTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipo', [$idTipo]);

        return parent::setIdTipo($idTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstado', []);

        return parent::getIdEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstado($idEstado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstado', [$idEstado]);

        return parent::setIdEstado($idEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAlumno($idAlumno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAlumno', [$idAlumno]);

        return parent::setIdAlumno($idAlumno);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAlumno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAlumno', []);

        return parent::getIdAlumno();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdParte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdParte', []);

        return parent::getIdParte();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdParte($idParte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdParte', [$idParte]);

        return parent::setIdParte($idParte);
    }

    /**
     * {@inheritDoc}
     */
    public function addIdParte(\AppBundle\Entity\Partes $idParte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdParte', [$idParte]);

        return parent::addIdParte($idParte);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdParte(\AppBundle\Entity\Partes $idParte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdParte', [$idParte]);

        return parent::removeIdParte($idParte);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaConfirmacion($fechaConfirmacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaConfirmacion', [$fechaConfirmacion]);

        return parent::setFechaConfirmacion($fechaConfirmacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaConfirmacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaConfirmacion', []);

        return parent::getFechaConfirmacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaComunicacion($fechaComunicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaComunicacion', [$fechaComunicacion]);

        return parent::setFechaComunicacion($fechaComunicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaComunicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaComunicacion', []);

        return parent::getFechaComunicacion();
    }

}
